language: swift
osx_image: xcode10.2

jobs:
    include:
        - stage: "Xcode"
          name: "Run tests on iOS"
          script: xcrun xcodebuild test -destination "platform=iOS Simulator,OS=12.2,name=iPhone X" -workspace "ReactiveKit.xcworkspace" -scheme "ReactiveKit-iOS"
          after_success: 'bash <(curl -s https://codecov.io/bash)'
        -
          name: "Build for macOS"
          script: xcrun xcodebuild build -destination "platform=macOS" -workspace "ReactiveKit.xcworkspace" -scheme "ReactiveKit-macOS"
        -
          name: "Build for tvOS"
          script: xcrun xcodebuild build -destination "platform=tvOS Simulator,OS=12.2,name=Apple TV 4K" -workspace "ReactiveKit.xcworkspace" -scheme "ReactiveKit-tvOS"
        -
          name: "Build for watchOS"
          script: xcrun xcodebuild build -destination "platform=watchOS Simulator,OS=5.2,name=Apple Watch Series 4 - 44mm" -workspace "ReactiveKit.xcworkspace" -scheme "ReactiveKit-watchOS"

        - stage: "Swift Package Manager"
          name: "Run Tests"
          script: swift test

        - stage: "CocoaPods"
          name: "Lint Podspec"
          script: pod lib lint
